---

- hosts: all
  vars_files:
    - "infras/global/vars/{{ aws_account }}.yml"
  roles:
  - base
  - nat

- hosts: nat
  vars_files:
    - "infras/global/vars/{{ aws_account }}.yml"
    - "infras/global/vars/{{ aws_account }}_{{ aws_region }}.yml"
  vars:
  roles:
  - base
  - nat
