---

# Local development playbooook
# ----------------------------

# A playbook for testing and integration.

# It will provision the `test` hosts in the inventory,
# which will, by default, specify the provided vagrant VM.

# This playbook should aim to test the most extensive
# or comprehensive configuration possible for your role.

# This should be in the tests folder but can't figure out how to get the references for roles correct.

- name: 'infra-nat setup'

  hosts: test

  vars:
    # custom_configuration: value
    pypi_scheme: https
    pypi_username: "{{ lookup('env', 'pypi_username') }}"
    pypi_password: "{{ lookup('env', 'pypi_password') }}"
    pypi_host: pypi.vandelay.io
    pypi_index: /balanced/prod/+simple/
    newrelic_license_key: foo

  pre_tasks:

    # Most vagrant boxes have outdated repositories
    - name: APT update
      sudo: yes
      apt: update_cache=yes

    - name: Make sure the dependencies are installed
      sudo: yes
      apt:
        pkg: "{{item}}"
        state: present
      with_items: ["python-virtualenv", "python-pip", "git", "python-dev"]

  tasks:

  handlers:

  roles:
    - base
    - nat
    - tests
